#!/bin/bash

source .env

./java-app/Home/bin/java -cp avctKVM.jar -Djava.library.path=$PWD com.avocent.idrac.kvm.Main \
 ip=$1 \
 vm=1 title=server-2,+PowerEdge+R620,++slot+,+User:+$USER user=$USER passwd=$PASSWD kmport=5900 vport=5900 apcp=1 chat=1 F1=1 custom=0 scaling=15 minwinheight=100 minwinwidth=100 videoborder=0 version=2